### ISSUE TITLE
Configuration?

### ISSUE THREAD

**Issue by zenny** [lepisma/org-krita#1]
Hi @lepisma ,

Nice macro. Yet could not figure out configuration info. Appreciate if you post.

Cheers, and stay safe,
/z

**Comment by Jdogzz** [comment]
On Linux the configuration is fairly simple:

1. Install org-krita with something like el-get or load it in your init file. Also make sure all the requirements are installed as mentioned in the org-krita.el file (side note: For my test install on Ubuntu the dependency is called `arc-mode` instead of `archive-mode` and that must be corrected in the org-krita.el file).
2. In an org file, make a new link like `[[krita:/home/myuser/kritafile.kra]]` after creating, with krita, that krita file at that location.
3. Activate the mode with `M-x org-krita-mode`
4. At this point it should display the image in-line, which can be clicked to open the source file in krita for editing.
5. After editing the file in krita as needed, save the file and it will be updated in the org file buffer. The file can be edited and updated as needed.

Unfortunately, I have not had this success in Windows. Currently I am facing two bugs: First, Windows will not display the image in-line (in Linux I see no text outputted to the Messages buffer, but in Windows I see a large amount of random text, so it seems like the extraction might be executed differently). Second, after clicking the blank square representing the image that isn't being displayed in line, krita is opened and I can make edits, but krita complains about being unable to write to the file (maybe when emacs incorrectly processes the kra file when attempting to display it, it never closes access to the file?). It would be good if the author could help debug where additional configuration is needed for use on Windows.

**Comment by lepisma** [comment]
Hi sorry for the delay and thanks for the help @Jdogzz 

1. fixed the arc-mode import via @coltoneakins 's PR

Not sure what's happening on Windows. I am not on windows but I am suspecting it (the not-able-to-save issue) might be because of the way filenotify works on windows vs linux since everything else looks platform agnostic. Can you confirm this by disabling file watcher set up call [here](https://github.com/lepisma/org-krita/blob/master/org-krita.el#L105) and try saving again?

**Comment by Jdogzz** [comment]
I can confirm that disabling the file watcher now allows saving to work properly on Windows, thank you for that.
